spring:
  datasource:
    replication:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      write:
        name: write
        url: jdbc:mysql://localhost:3307/test_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      reads:
        - name: read1
          url: jdbc:mysql://localhost:3308/test_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
