version: "3.8"

services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-net

  replica:
    image: mysql:8.0
    container_name: mysql-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./replica/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-net
    depends_on:
      - master

networks:
  mysql-net: