apiVersion: v1
kind: Secret
  url: jdbc:mysql://localhost:3307/test_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true

metadata:
  name: admin-secret

stringData:
  db_url: jdbc:mysql://portfolio-dev.cp4auok2edwx.ap-northeast-2.rds.amazonaws.com:3306/test_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
  db_username: admin
  db_password: wjdwo15975